### ISSUE TITLE
Please format this code consistently, including the examples

### ISSUE THREAD

**Issue by cculianu** [micro-gl/micro-gl#39]
```c++
    template<typename BlendMode=blendmode::Normal,
            typename PorterDuff=porterduff::FastSourceOverOnOpaque,
           microgl::ints::uint8_t a_src>
```

What is this?

Or this:

```c++
    void updateCanvasWindow(int left, int top, int right, int bottom) {
        _window.canvas_rect = {left, top, left + right, top + bottom };
        _window.index_correction= _window.canvas_rect.width()*_window.canvas_rect.top
                                  + _window.canvas_rect.left;
```

Nobody ever does `a= val`.  And it's not even consistent sometimes you do `a = val`, sometimes `a=val` and sometimes the odd `a= val`.  

Also, inconsistent spacing around operators...  Sometimes it's `a * b` sometimes `a*b` depending on your whim.

Also inconsistent indentation inside function parameter  lists, inconsistent `Type &var` (sometimes it's `Type & var`), etc...

Please learn to use clang-format or something.

**Comment by HendrixString** [comment]
@cculianu Definitely, maybe you can recommend a me a good way to do so ?
I use clion IDE

**Comment by HendrixString** [comment]
@diamant3 Do you know of a good way to enforce formatting?

**Comment by cculianu** [comment]
You can use the CLI program `clang-format` or you can turn on auto-format in CLion or select blocks of text and ask it to autoformat.  I like `clang-format` because you can control the formatting yoruself.  Attached is a sample `.clang-format` configuration file. You can look at what all the options do and get it to align everything the way you want it.  Here is a sample file attached.  You need to rename it to `.clang-format` and put it in your home dir to use it.. this is just an example you may want to play with the options to suit your personal style.  Note it can also align variabels and macro defs as I see you like do to in your codebase.. (this sample file has that turned off but you may want to turn it on).

[dot_clang-format.gz](https://github.com/user-attachments/files/15917755/dot_clang-format.gz)

**Comment by HendrixString** [comment]
@cculianu Thank you 🙏 man, I appreciate it.
I will play with it next week. I definitely care for formatting aesthetics.

**Comment by diamant3** [comment]
yes +1 to `.clang-format`, recommended.👍🏼
