### ISSUE TITLE
Add ::drawPath with perspective, like drawQuadrilateral

### ISSUE THREAD

**Issue by hadjTahar** [micro-gl/micro-gl#41]
Really appreciate this library.

Can you add drawPath with perspective, like drawQuadrilateral does, it will be handy to draw custom 2D shapes that can rotate around an axis instead of a point.
Or at least show how to create one.

Thanks.

**Comment by HendrixString** [comment]
Hi @hadjTahar ,

Every canvas draws to a bitmap.
So, you can use two canvases.

At the first canvas, you draw the path.

And at the second canvas you draw a quadrilateral using the bitmap of the first canvas.

**Comment by hadjTahar** [comment]
Thanks for the prompt response.
That makes sense I will try it.
But will there be a performance hit if I use something like this


```
Canvas mainCanvas( width, height ); 
renderLoop()
	// Is the constructing Canvas with each render call hinders the performance
	// This is called for many objects or items
	Canvas smallCanvas( pathWidth, pathHeight ); 
	smallCanvas.drawPath();
	mainCanvas.drawQuadrilateral( smallCanvas.bitmap );

```

**Comment by HendrixString** [comment]
Hi,

Ask yourself the following question,
Does the path remain static ?
If so, it can be computed once and then reused as a bitmap.

If it is not static, you will still be fine I guess

**Comment by hadjTahar** [comment]
Hi, I got it working, thanks.

When I do `auto bitmap = pathCanvas.bitmapCanvas();`, I get this error:

`error: binding reference of type 'bitmap<microgl::coder::RGBA_PACKED<8, 8, 8, 0> >&' to 'const bitmap<microgl::coder::RGBA_PACKED<8, 8, 8, 0> >' discards qualifiers`

I tried `const auto bitmap`, `const auto& bitmap` and the error still remains.

I had to change `bitmap_type &canvas::bitmapCanvas() const;` to `const bitmap_type &canvas::bitmapCanvas() const;` in `canvas.h` for it to work for me.

I am using MinGW 6.7 64bit.

And an other question, I noticed that `canvas::clear` is taking most of the CPU usage is there a way to optmimize it like only clear portions, this way only the pixels that need updates will get cleared and not the whole canvas

**Comment by HendrixString** [comment]
@hadjTahar 
I am not sure about the first problem, will have to check.

The second ask, quite simply there is an updateRect method or something similar you can use before clearing, and then after clearing you can update it again

**Comment by HendrixString** [comment]
@hadjTahar maybe also try auto const &

**Comment by hadjTahar** [comment]
You can't overload with the return type, so this is what I came up with
    `bitmap_type &bitmapCanvas(); // Non const`
    `const bitmap_type &bitmapCanvas() const;  // const`

Last question if you don’t mind, how should drawing out of range on the canvas be handled?

For example if I draw a rectangle with negative values or values bigger than the canvas’s size.
Is it on me to check if the vertices are within range, or that’s handled internally and I should not worry about it?

**Comment by HendrixString** [comment]
@hadjTahar this is the overload I meant.

Also, microgl takes care for drawing outside the canvas, it clips the drawing, so don't worry
